### ISSUE TITLE
Feature request - Compress images to shrinnk library

### ISSUE THREAD

**Issue by ElMouse** [avluis/Hentoid#1157]
Just a feature request which might be useful.

The feature is to compress images stored on device to downscale library. 
There are some books out there with 250 pages ~2mb page each - and lots of them. Usually good ones.
As one could imagine - one such book would take up 500mb of space. 10 such books and its 5gb. you get the idea.

A function "Lower size of this book" with simple parameter "lower the pages with and heght sizes in this book to <slider percent> %" Could really help folks out there to preserve valueble space. 

In the above example the book could easily be downsized 5x times to 100mb without visible image quality degradation.

Now, one would think - "there are obviously apps out there to do this not involving hentoid"

Surpsisingly, having researched - i found that there are no apps there that do just that. They are other plagued by ads or requests to but premium and still work and feel awful. Either you need to copy files somewhere beforehand, than apply resizing, then move files back. Some of them reame files, and so on and so on. It is just strictly painful.

And if you manage to somehow achieve shrinking after manually searching for books folder in android filesystem, painfully moving files back and forth, struggling with buggy apps, spending like 10 minutes for one book, finally - you actually shrinked the book. And it works in hentoid. Still, hentod shows original size of the book...

Thanks.

The app is genious by the way. I LOVE it.

**Comment by ArturRA** [comment]
Hello, you will be glad to know that this feature already exist in Hentoid.

On the library screen select a book, then click on the three dots at the top right and select transform. Now you can transform the file type of the pictures, upscale the pictures or downscale the pictures(your requested feature). If you need any help using the feature you are welcome to ask your question in the help channel in our discord. ^^

Ps: The reason that if you shrink the files using an external app and the changes in size aren't reflected in Hentoid is because those changes don't update the .json file inside each book's folder that contain the info about that book. So even though the book was shrank outside the app that info change won't reflect on Hentoid unless you manually update the .json file.

**Comment by ArturRA** [comment]
No worries, I am glad you are enjoying the app and have a nice day. ^^
