### ISSUE TITLE
External storage issues 

### ISSUE THREAD

**Issue by Patgoo** [avluis/Hentoid#132]
**Hentoid Version**:Hentoid v1.2.1r2 

**Device/Android Version**: galaxy s7 edge/6.0.1

**Issue details / Repro steps**: after setting up the app to read from my memory card the app gives the generic "app not responding do you want to wait/close."

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
``` 

@AVnetWS/admin-team

**Comment by avluis** [comment]
The app has had limited testing on Samsung devices -- do you know how to gather a logcat?
If you don't mind putting in some time to figure out the issue on your device, can you join our Discord server? You can catch me in there at reasonable hours (I'm in US Central Time).

**Comment by Patgoo** [comment]
How do I join your server

**Comment by avluis** [comment]
@Patgoo I stealthily added the link to my reply above but here it is again so that you see it on your inbox -- note that I'm a bit busy tonight so I won't be able to jump on this issue right away, but rather sometime tomorrow or so if that is OK with you~
Here is the link: https://discord.gg/0yFzSPtXehJmFqOM

**Comment by RobbWatershed** [comment]
This issue has been inactive for more than two years and the app has evolved tremendously since v1.2.1r2 => Issue closed
