### ISSUE TITLE
Annoying Scroll Bug

### ISSUE THREAD

**Issue by MrSwabe90** [avluis/Hentoid#134]
**Hentoid Version**:1.2.1r2

**Device/Android Version**:Huawei P9lite 6.0 EMUI 4.1.1

**Issue details / Repro steps**:When you scroll your download page, endless mode or page mode, it would show "Go on, download something" after. It's kinda annoying. It works last time by gently scrolling, but now it won't. I can't read my earlier downloads 😥

**Stack trace / LogCat**: Sorry I still don't know how to do this. 
```ruby
paste stack trace and/or log here
```

Me doing it rough:
        https://youtu.be/lOIAZck6PbE
Me doing it gently:
        https://youtu.be/lOIAZck6PbE

@AVnetWS/admin-team

**Comment by avluis** [comment]
There have been some scrolling improvements already implemented in the current dev branch (I was already aware of the scrolling issues).
I still want to improve that a bit more, which is why there has not been an update pushed out with said fixes.

Most of the issues here is dealing with slower SD Cards (internal and external) and loading from the database.
Anyways, thank you for documenting this.

**Comment by MrSwabe90** [comment]
That's good to hear. Thanks for the update.
