### ISSUE TITLE
Nhentai content urls with id ending in `1` are truncated (new downloads)

### ISSUE THREAD

**Issue by wightwulf1944** [avluis/Hentoid#352]
Affects v1.8.5 and is 100% reproducible

**Repro steps:**
1. download any nhentai content with it's id ending in `1`
2. once downloaded, tap on the web icon to open it in the app browser

**Actual result:**
Given content with the url https://nhentai.net/g/99991/, it opens https://nhentai.net/g/9999 instead

length of the content id does not seem to affect the repro rate

**Comment by RobbWatershed** [comment]
Need to code an auto-repair to fix existing books

**Comment by RobbWatershed** [comment]
Unfortunately, the truncated ID is saved all over the app, which prevents any easy fix for downloaded books.

The only remaining way of fixing the issue would be to interact with nHentai itself, something along the lines of :
1- Inspect nHentai books downloaded since the release date of v1.8.5
2- Query nHentai with the saved book ID and see if titles match
3- If not, add `1` to book ID and retry step 2
4- If titles match, save updated book ID

**Comment by RobbWatershed** [comment]
Issue fixed for newer downloads; wontfix for downloaded books (see #371)
