### ISSUE TITLE
Hitomi - Images not found [Svenhent]

### ISSUE THREAD

**Issue by RobbWatershed** [avluis/Hentoid#396]
Download of some books fail during gallery parsing

e.g. 1505095

**Comment by ryj0902** [comment]
The error seems to only occur on books uploaded from October 19, 2019. 
(Books uploaded on day 18 were verified to download correctly)

Here, attach full [error log](https://github.com/avluis/Hentoid/files/3756999/error.log)

**Comment by ryj0902** [comment]
It seems that the HTML form of Hitomi reader has changed since the book uploaded on a certain date.
Is it because "Parser" could not find the address of the image to load because the "img-url" class has been removed?
I have confirmed that all books with that class exist can be downloaded properly.

ex) 1504283 uploaded Oct 20, 2019 6:30 AM, have "img-url" class , succeeded in downloading.
1503841 uploaded Oct 19, 2019 9:13 AM, but doesn't have "img-url" class, fails to download.

Features: No images downloaded and exit as soon as they enter the download queue.
Books appear on top when sorted by download date (oldest 1st).
Total images in download are always 0.

**Comment by ryj0902** [comment]
I think this codes are problem because of the above changes.

https://github.com/avluis/Hentoid/blob/1e162eb01f27280909679303c751cdd52e0f90b1/app/src/main/java/me/devsaki/hentoid/parsers/HitomiParser.java#L39-L40

**Comment by RobbWatershed** [comment]
Thanks for the tip man, highly appreciated 👍 👍

**Comment by RobbWatershed** [comment]
Looks like the newer books have non-linear page numbers

**Comment by RobbWatershed** [comment]
Will be fixed very soon. There's a release candidate to test on our Discord channel.

**Comment by RobbWatershed** [comment]
Fix available in v1.9.2
