### ISSUE TITLE
Download button doesn't show on Hitomi

### ISSUE THREAD

**Issue by RobbWatershed** [avluis/Hentoid#400]

**Comment by ryj0902** [comment]
Is this a problem caused by parser-blocking or another reason?

From a very simple point of view, the problem is that code can't go beyond the first if statement in a function of **processContent**. (Probably if we uncomment line 745 and 748, we can see it more clearly) https://github.com/avluis/Hentoid/blob/1b5d5e5ada1acbbc535168607e1f648fa4e1ba07/app/src/main/java/me/devsaki/hentoid/activities/sources/BaseWebActivity.java#L744-L748
Because of this, 
 -> onResultReady on line 758 is not called
 -> processContent on line 524 is not called
 -> message on line 493 does not occur
 -> and in conclusion, changeFabActionMode function is not called.
(Debugging was done in the exact opposite order)

Testing on TSUMINO showed no parser-blocking errors, and all of the above functions were called.

**Comment by ryj0902** [comment]
I don't know if it helps, but I'll attach the logs I found during debugging > [log.txt](https://github.com/avluis/Hentoid/files/3785343/log.txt)

**Comment by RobbWatershed** [comment]
Thanks a lot for trying to help me man :)

I've found the solution

**Comment by RobbWatershed** [comment]
Fixed by 1d222d790460cb01d3ca95c6ae9442e7fc521935
