### ISSUE TITLE
Books from external library show up blank

### ISSUE THREAD

**Issue by quankquank** [avluis/Hentoid#634]
**Hentoid Version**: 1.12.5 (254)

**Device/Android Version**: Sharp Aquos R Compact | Softbank 701SH on Android 9

**Issue details / Repro steps**: Books imported from external library (SD card) doesn't show any images. The app does get the book name and the number of pages correct, but shows 0.0 MB in every book and none of the picture show up - they're all black screen. I can still navigate around, which probably mean the app doesn't crash. I checked the book folder and they all had a contentV2.json file created

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

![Screenshot_20200821-142519](https://user-images.githubusercontent.com/55222640/90864176-6a982700-e3ba-11ea-961e-58aff63dfe8c.png)

@AVnetWS/admin-team

**Comment by RobbWatershed** [comment]
Hey there and thanks for the report. It is a known bug and only happens when refreshing the external library after importing it for the 1st time.
A fix will be released in the following week. 

For the time being, you can remove the Contentv2.json files from your external library folders and reimport them.

**Comment by RobbWatershed** [comment]
Duplicate from #625
