### ISSUE TITLE
Download All Doujinshis at the Page

### ISSUE THREAD

**Issue by kana717** [avluis/Hentoid#663]
Can you add something like this? Downloading all doujinshis at the Website's page?

**Comment by RobbWatershed** [comment]
Unfortunately, that won't be done because :
- mass-downloading that _will_ follow has a high chance of triggering a security response on the websites, which will become more difficult to parse
- that feature requires not only to maintain compatibility with evolving gallery pages, but also with results pages. The Hentoid team doesn't have the manpower to maintain that feature over time

**Comment by RobbWatershed** [comment]
If you're in a hurry to download everything, you can still use quick download (long tap on a book cover -> added to queue immediately without having to visit the gallery page)

**Comment by kana717** [comment]
I didn't know that thanks
