### ISSUE TITLE
Networking Error Occurs

### ISSUE THREAD

**Issue by Magnus6432** [avluis/Hentoid#690]
**Hentoid Version**: v1.12.9

**Device/Android Version**: Galaxy S10+

**Issue details / Repro steps**: Many products have same issues, and I can't download it even i redownload them many times.

**Stack trace / LogCat**:
```ruby
Networking - Server error; HTTPstatusCode=404; message=null
``` 

@AVnetWS/admin-team

**Comment by RobbWatershed** [comment]
Getting a 404 is not linked to your device at all; it means the app can't find the image on the site.

- If you're on Nexus, it's "normal", Nexus has been super unstable for a long time. Just be patient and retry later
- If you're living in one of those countries whose government block these sites, use a good VPN (see https://thatoneprivacysite.net/vpn-comparison-chart/)
- If you're sure about your connection and you're not targeting Nexus, then I recommend you join us on Discord and post one of your error logs, so that we can discuss it together

**Comment by Arklimits** [comment]
Can you remove this issue?

I want to hide this contribution from my profile, but I figured out it's not allowed to remove the issue by me.

**Comment by Arklimits** [comment]
Hello Mr.

Can you remove this issue?

I wanted to hide this issue from contributions, but I figured out there's no way to hide it.

**Comment by avluis** [comment]
Removing issue per user request 😭
