### ISSUE TITLE
Some new chapters from fakku don't appear in hentoid.

### ISSUE THREAD

**Issue by Knobibrot** [avluis/Hentoid#737]
**Hentoid Version**: 1.13.8

**Device/Android Version**: Samsung Galaxy A20e/A202FXXU3BTK2

**Issue details / Repro steps**: I have noticed that some newish chapters from fakku can not be found when I search for them with hentoid. Examples include "Combo" from Karma Tatsuro and "Boobie New Year" from BoBoBo.
It's possible that it's completely normal that there is a delay; I wouldn't know since I'm a new user of hentoid. But it is a bit odd that some other, even newer chapters appear in hentoid while these don't.

@AVnetWS/admin-team

**Comment by RobbWatershed** [comment]
Where are you searching exactly? Try to be as precise as possible

**Comment by Knobibrot** [comment]
I pick the fakku tab in hentoid. Then I search for the title in the search at the top but the chapter doesn't show up. Then I go to the artist's page in fakku. The list of chapters is missing the chapter in question (the latest) but seems to have all the others.

**Comment by RobbWatershed** [comment]
That's super odd indeed.

Hentoid doesn't do anything on the Fakku tab - it more or less displays the Fakku site like any other browser would do.
If I had to guess, what you're seeing might be due to the fact that Hentoid accesses the _mobile_ Fakku site and not the _desktop_ Fakku site.

Do you have the same issue when opening Fakku with your Chrome app (or any other mobile browser) ?

**Comment by Knobibrot** [comment]
Yes, indeed. If I open fakku on my mobile phone in a browser these chapters are not visible.

**Comment by RobbWatershed** [comment]
Case solved then. The Hentoid browser should be able to switch to the desktop version of its sites in a future update (see #677).

Until then I fear we can't do much to help.
