### ISSUE TITLE
Need changes of saved comics library.

### ISSUE THREAD

**Issue by lolruler** [avluis/Hentoid#745]
I'm using the latest version of hentoid .
The issue i like to talk is about this app library, this library is sucks.. make awesome lile tachiyomi.in tachiyomi i can rearrange my favorite comics at my separate category example loli staff are categorized at loli room and milf staff are categorized at milf room/library. But this app's category system is not good enough
Please make it more easy to use and stable .thank you...

**Comment by RobbWatershed** [comment]
Thanks for leaving your feedback.

There are a few things I'd like to react on :

- We can't debate over the library itself and its numerous improvements-to-be in one single Github issue. As you may have seen, Github is a tool for developers; each issue needs to address one problem, not an entire screen. If you want to debate in a more open form, you're welcome to join our Discord community 😄 

- Have you seen Hentoid has a feature that allows you to sort your books into custom groups (like the "loli" and "milf" examples you just gave) ?  Long tap on a book > top menu > Move to group

- To be perfectly honest with you, "Please make it easier to use" won't lead anyone anywhere. Please do take inspiration on the other existing issues to describe in precise terms what would be an improvement to you. And saying "just do as Tachiyomi does" is not an option, as it is wildly open to interpretation (what does Tachiyomi do right ? what does it do wrong ? what's to take and to leave in their current UI and model ?).

- Stability has been a concern since day one. We do follow the app's metrics regularly and are fully aware of the current stability issue on the library and queue screens. As it is technically difficult to reproduce in our development environment, we are trying to pinpoint it by trial and error, as you may have noticed. Please be patient until it is eradicated.
