### ISSUE TITLE
Hentai2Read ads again

### ISSUE THREAD

**Issue by runboy93** [avluis/Hentoid#769]
Open Hentai2Read > choose any doujin from first page

After "Discussion" spot, under there are random sponsored ads from "runative"

Tested on latest stable hentoid.

**Comment by Kadantte** [comment]
Well, ads are tricky! ADS operators always change their domain so It's hard to block it all! anyway, wait for the next release the devs will fix it! Also, I checked with `Hentoid` and `Hentoid-Beta` there are some ads but It's okay tbh since all the ads are at the bottom of the page try to download the book and read from `Hentoid` reader 😄!

**Comment by RobbWatershed** [comment]
As the man said, more ads have been removed in the latest beta. That will be made available as soon as next relase.
Thanks for your feedback anyway 😉
