### ISSUE TITLE
The is downloading the books with 0 pages

### ISSUE THREAD

**Issue by Vageto12** [avluis/Hentoid#793]
Hentoid Version: 1.14.4 (358)

i have the Mi 8 Lite that runs MIUI 12

Ok so i moved the hentoid folder to my sd card              (i selected it from the app to be the new folder) because my device was low on space and i had no problem with the books i had already downloaded, but when i tried to download new ones they downloaded with 0 pages. Though some pages were downloaded, there were a lot of them that were missing.

Sry for my bad english.

**Comment by RobbWatershed** [comment]
Hi and thanks for your feedback !

Could you describe what happens when downloading with a little more details ?

Most importantly : what happens when the download is completed ? Does the book appear in the library or appears on the Errors tab of the queue screen ?

If in the library : where can you see there are 0 pages ?

If in the errors tab of the queue screen: could you please upload the error log ?

**Comment by RobbWatershed** [comment]
Closed because no feedback from the OP since May 15th
